### PR TITLE
Added `limit` option, Updated example and eslinting, Upgraded deps

### PR DESCRIPTION
**Pull request by niftylettuce**

### CODE REVIEW

**Comment by niftylettuce** [comment]
Can you please accept this PR @scttcper and then release a new version to npm and ping me?  Thank you.

**Comment by scttcper** [comment]
@niftylettuce published under 2.4.0

**Comment by niftylettuce** [comment]
thanks @scttcper!  if you wanted to give me npm ownership access too I can help publish and maintain npm versions for future maintenance.  up to you!  `npm owner add niftylettuce koa-simple-ratelimit`

**Comment by scttcper** [comment]
@niftylettuce done

**Pull request merged**
